// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('D:/CODE/PROJECTS/icones/src/components/ActionsMenu.vue')['default']
    Bag: typeof import('D:/CODE/PROJECTS/icones/src/components/Bag.vue')['default']
    CollectionEntries: typeof import('D:/CODE/PROJECTS/icones/src/components/CollectionEntries.vue')['default']
    CollectionEntry: typeof import('D:/CODE/PROJECTS/icones/src/components/CollectionEntry.vue')['default']
    ColorPicker: typeof import('D:/CODE/PROJECTS/icones/src/components/ColorPicker.vue')['default']
    DarkSwitcher: typeof import('D:/CODE/PROJECTS/icones/src/components/DarkSwitcher.vue')['default']
    Drawer: typeof import('D:/CODE/PROJECTS/icones/src/components/Drawer.vue')['default']
    FAB: typeof import('D:/CODE/PROJECTS/icones/src/components/FAB.vue')['default']
    Footer: typeof import('D:/CODE/PROJECTS/icones/src/components/Footer.vue')['default']
    HelpPage: typeof import('D:/CODE/PROJECTS/icones/src/components/HelpPage.vue')['default']
    Icon: typeof import('D:/CODE/PROJECTS/icones/src/components/Icon.vue')['default']
    IconButton: typeof import('D:/CODE/PROJECTS/icones/src/components/IconButton.vue')['default']
    IconDetail: typeof import('D:/CODE/PROJECTS/icones/src/components/IconDetail.vue')['default']
    Icons: typeof import('D:/CODE/PROJECTS/icones/src/components/Icons.vue')['default']
    IconSet: typeof import('D:/CODE/PROJECTS/icones/src/components/IconSet.vue')['default']
    Modal: typeof import('D:/CODE/PROJECTS/icones/src/components/Modal.vue')['default']
    ModalDialog: typeof import('D:/CODE/PROJECTS/icones/src/components/ModalDialog.vue')['default']
    Navbar: typeof import('D:/CODE/PROJECTS/icones/src/components/Navbar.vue')['default']
    NavElectron: typeof import('D:/CODE/PROJECTS/icones/src/components/electron/NavElectron.vue')['default']
    NavPlaceholder: typeof import('D:/CODE/PROJECTS/icones/src/components/electron/NavPlaceholder.vue')['default']
    Notification: typeof import('D:/CODE/PROJECTS/icones/src/components/Notification.vue')['default']
    Progress: typeof import('D:/CODE/PROJECTS/icones/src/components/Progress.vue')['default']
    SearchElectron: typeof import('D:/CODE/PROJECTS/icones/src/components/electron/SearchElectron.vue')['default']
    WithNavbar: typeof import('D:/CODE/PROJECTS/icones/src/components/WithNavbar.vue')['default']
  }
}

export { }
